function iconSvg(name){const paths={governance:'<path d="M4 5h16v14H4zM8 9h8M8 13h5"/>',privacy:'<path d="M2.5 12s3.3-6 9.5-6 9.5 6 9.5 6-3.3 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.6"/>',ethics:'<path d="M12 3v18M5 6h14M7 6l-4 7h8zM17 6l-4 7h8zM8 21h8"/>',security:'<path d="M12 3 20 6v5c0 5-3.2 8-8 10-4.8-2-8-5-8-10V6z"/><path d="M9 12h6M12 9v6"/>',verity:'<path d="M6 3h9l4 4v14H6zM15 3v5h5M9 14l2.2 2.2L16 11"/>'};return `<svg class="line-icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.governance}</svg>`;}
const modules={governance:{name:'Governance',kicker:'Decision rights and accountability',icon:'governance',text:'Turn policy into operating decisions that people can own, evidence and repeat. Governance is the foundation for scaling AI without adding unnecessary bureaucracy.',out:['Named ownership for AI-enabled processes','Decision records connecting policy to action','Configurable approval and escalation routes'],use:'Best for leaders who need a clear operating model before expanding AI adoption.'},privacy:{name:'Privacy',kicker:'Proportionate and visible data use',icon:'privacy',text:'Make data use visible, intentional and proportionate. Privacy controls help teams understand what is being used, why it is needed and where accountability sits.',out:['Purpose and use visibility','Data handling controls for workflows','Clear routes for review and exception'],use:'Best for organisations managing sensitive, personal or customer data.'},ethics:{name:'Ethics',kicker:'Responsible choices in the workflow',icon:'ethics',text:'Move responsible AI from a statement of intent into everyday workflow choices, with practical checks for impact, fairness, human oversight and escalation.',out:['Human oversight at the right point','Impact and fairness prompts','Escalation for higher-risk decisions'],use:'Best for teams introducing automation into customer, employee or public-facing decisions.'},security:{name:'Security',kicker:'Resilience and control by design',icon:'security',text:'Connect AI activity to practical security and resilience controls so access, change, incident and continuity decisions are made deliberately.',out:['Access and control alignment','Security review triggers','Resilience and incident routes'],use:'Best for technology, cyber and risk leaders governing a growing AI estate.'},verity:{name:'Verity',kicker:'Evidence that can be trusted',icon:'verity',text:'Verity provides the assurance layer across Counterpoise. It creates durable evidence that controls operated, decisions were made and the state of a workflow can be understood later.',out:['Evidence records for key control points','Drift and change visibility','Assurance information for boards and reviewers'],use:'Best for regulated, high-impact or assurance-led adoption.'}};
const scenarios={sme:{title:'A proportionate route for an SME',text:'A small or growing organisation can start with Governance and Privacy around one priority workflow, then add Verity evidence as usage grows. The operating model stays understandable while the control surface expands with the business.',pills:['Start with one workflow','Named accountable owner','Scale by module','Low-friction adoption']},enterprise:{title:'A coordinated control model for enterprise risk',text:'An enterprise risk leader can use Counterpoise to align governance, privacy, ethics and security across teams and suppliers, while Verity provides a consistent assurance thread for senior reporting and review.',pills:['Cross-functional ownership','Policy-to-control mapping','Supplier and workflow visibility','Board-ready evidence']},product:{title:'A safer path from experiment to product',text:'A product and data leader can move promising AI experiments into governed delivery by defining decision points, human oversight, security expectations and evidence requirements before the workflow reaches customers.',pills:['Experiment-to-production route','Human-in-the-loop','Release confidence','Reusable controls']}};
const verityAssets=[
  {asset:'Customer risk model inputs',type:'Model / decision',owner:'Data Products',evidence:'22 Sep 2026',state:'Drifted',filter:'attention'},
  {asset:'Supplier sustainability dataset',type:'External dataset',owner:'Procurement',evidence:'21 Sep 2026',state:'Changed pending',filter:'attention'},
  {asset:'Customer onboarding checks',type:'Workflow evidence',owner:'Operations',evidence:'22 Sep 2026',state:'Assured',filter:'assured'},
  {asset:'AI service performance pack',type:'Monitoring record',owner:'Technology',evidence:'20 Sep 2026',state:'Assured',filter:'assured'},
  {asset:'Quarterly board evidence pack',type:'Assurance presentation',owner:'Risk Office',evidence:'19 Sep 2026',state:'Assured',filter:'assured'},
  {asset:'Employee impact assessment',type:'Ethics / impact',owner:'People & Culture',evidence:'18 Sep 2026',state:'Assured',filter:'assured'}
];
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.dataset.panel===v));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo({top:0,behavior:'smooth'});}
function go(el){el.addEventListener('click',()=>view(el.dataset.go));}
function cards(){document.getElementById('homeCards').innerHTML=Object.entries(modules).map(([k,m])=>`<article class="card"><div class="card-top"><div class="icon">${iconSvg(k)}</div><span class="status">${k==='verity'?'Assurance':'Ready'}</span></div><h3>${m.name}</h3><p>${m.text.split('.')[0]}.</p><button class="link" data-go="modules">Explore <span>→</span></button></article>`).join('');document.querySelectorAll('[data-go]').forEach(go);}
function detail(k){const m=modules[k];document.getElementById('detail').innerHTML=`<div class="detail-kicker">${m.kicker}</div><h2>${m.name}</h2><p class="detail-copy">${m.text}</p><div class="detail-columns"><div class="detail-block"><h4>Practical outcomes</h4><ul>${m.out.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="detail-block"><h4>Good starting point</h4><p class="detail-copy" style="font-size:12px">${m.use}</p><button class="primary small" data-go="scenarios">See a scenario <span>→</span></button></div></div>`;document.querySelectorAll('[data-go]').forEach(go);}
function moduleList(){document.getElementById('moduleList').innerHTML=Object.entries(modules).map(([k,m],i)=>`<button class="module-row ${i?'':'selected'}" data-key="${k}"><span class="icon">${iconSvg(k)}</span><span><h3>${m.name}</h3><p>${m.kicker}</p></span></button>`).join('');detail('governance');document.querySelectorAll('.module-row').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.module-row').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');detail(x.dataset.key)}));}
function scenario(k){const s=scenarios[k];document.getElementById('scenarioOut').innerHTML=`<h3>${s.title}</h3><p>${s.text}</p><div class="pills">${s.pills.map(x=>`<span>${x}</span>`).join('')}</div>`;}
function assetState(state){const key=state.toLowerCase().replace(' ','-');return `<span class="asset-state ${key}"><i></i>${state}</span>`;}
function renderAssets(filter='all'){const rows=verityAssets.filter(a=>filter==='all'||a.filter===filter).map(a=>`<div class="asset-row"><span><b>${a.asset}</b><small>${a.type}</small></span><span>${a.owner}</span><span>${a.evidence}</span><span>${assetState(a.state)}</span><span class="row-arrow">→</span></div>`).join('');document.getElementById('assetRows').innerHTML=rows;}
document.querySelectorAll('.nav').forEach(x=>x.addEventListener('click',()=>view(x.dataset.view)));document.querySelectorAll('[data-go]').forEach(go);document.querySelectorAll('.scenario').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.scenario').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');scenario(x.dataset.scenario)}));document.querySelectorAll('.filter').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(y=>y.classList.remove('active'));x.classList.add('active');renderAssets(x.dataset.filter)}));document.getElementById('reset').addEventListener('click',()=>{view('overview');scenario('sme');document.querySelectorAll('.filter').forEach((x,i)=>x.classList.toggle('active',i===0));renderAssets()});cards();moduleList();scenario('sme');renderAssets();

document.querySelectorAll('.diagram-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.diagram-tab').forEach(x=>{const active=x===tab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));});document.querySelectorAll('.system-figure').forEach(fig=>fig.classList.toggle('active',fig.dataset.figure===tab.dataset.diagram));}));

const walletFeedback=document.getElementById('walletFeedback');document.getElementById('preparePresentation').addEventListener('click',()=>{walletFeedback.textContent='Preview ready: selected assurance claim and decision receipt only. Audience, purpose and expiry would be confirmed before any real presentation. Nothing was sent.';});document.getElementById('revokeCredential').addEventListener('click',()=>{walletFeedback.textContent='Demo status updated: this illustrative credential is marked revoked locally. No real credential or stored record was changed.';});

document.querySelectorAll('.diagram-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.diagram-tab').forEach(x=>{const active=x===tab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));});document.querySelectorAll('.system-figure').forEach(fig=>fig.classList.toggle('active',fig.dataset.figure===tab.dataset.diagram));}));
